"""Add lucro and valor_venda_sugerido to Produto

Revision ID: 3ebfb919085e
Revises: 3fd01ffe541a
Create Date: 2025-05-19 00:20:41.515642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ebfb919085e'
down_revision = '3fd01ffe541a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lucro', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('valor_venda_sugerido', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produto', schema=None) as batch_op:
        batch_op.drop_column('valor_venda_sugerido')
        batch_op.drop_column('lucro')

    # ### end Alembic commands ###
