"""Migração correta PostgreSQL

Revision ID: 514a6d4f43bf
Revises: 3ebfb919085e
Create Date: 2025-05-24 10:15:26.979020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '514a6d4f43bf'
down_revision = '3ebfb919085e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
