"""Adicionar colunas custo_manutencao, custo_frete e custos_extras

Revision ID: f89fff259ca1
Revises: ab94e970a228
Create Date: 2025-05-18 22:09:10.341948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f89fff259ca1'
down_revision = 'ab94e970a228'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('custo_manutencao', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('custo_frete', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('custos_extras', sa.Float(), nullable=True))
        batch_op.drop_column('servicos_extras')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('servicos_extras', sa.FLOAT(), nullable=True))
        batch_op.drop_column('custos_extras')
        batch_op.drop_column('custo_frete')
        batch_op.drop_column('custo_manutencao')

    # ### end Alembic commands ###
